# Generated by Django 3.1.4 on 2021-08-16 14:56

import clients.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20210816_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='kpp',
            field=clients.models.KPP(),
        ),
        migrations.AlterField(
            model_name='client',
            name='ogrn',
            field=clients.models.OGRN(),
        ),
    ]
