# Generated by Django 3.1.4 on 2021-08-16 15:02

import clients.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20210816_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='inn',
            field=clients.models.INNB(mode='legal'),
        ),
    ]
